language: node_js
node_js:
  - stable

#before_install:
#  - git config --global user.email "travis@travis-ci.org"
#  - git config --global user.name "Travis CI"
script:
  - npm run build
after_success:
  - SOURCE_BRANCH="master"
  - TARGET_BRANCH="gh-pages"
  - SOURCE_DIR=${PWD##*/}
  - TARGET_DIR=$TARGET_BRANCH
  - REPO=`git config remote.origin.url`

  # Clone my repo one folder up for gh-pages version
  - cd ..
  - git clone $REPO $TARGET_DIR --branch $TARGET_BRANCH --single-branch --depth 1
  - cd $TARGET_DIR

  # set remote on gh-pages version

  # clean (remove unchecked in files) gh-page version
  - git clean -f -d

  # fetch and Checkout gh-page branch
  - git fetch origin

  # remove existing files
  - rm -rf ./*

  # copy files from dist to gh-page branch
  - cp -R ../$SOURCE_DIR/dist/* ../$TARGET_DIR

  # setup user
  - git config user.name "Travis CI"
  - git config user.email "travis@travis-ci.org"

  # set github access token
  - git config github.token $github_token

  # Add files
  - git add .

  # commit changes
  - git commit -m "Travis Deploy, travis build $TRAVIS_BUILD_NUMBER"

  # push
  - git push https://tmburnell:$GITHUB_API_KEY@github.com/tmburnell/ng2-json-schema-builder $TARGET_BRANCH

env:
  global:
    secure: khf1dnwQHhJJFq/susIJWCZzFwwfnfUmzrmzxpKphk8shPqqEOt7arYAzmpz7jnNeqc3d7vdcCk2+Q/bkXQX7TBMwSTLuqG3Bf+LRthViNu9sYQwZS4+n+GERYzYqqEid0rWItsE1gBZ/TTI5gI2Ev+hcpcMayFaW6m7DuWjQ11bkAIFmOmHqwOFxZWCQtsAaGhmk69hPyXYQMwJQSMrsFXn3yFcQsrTh2JX0LIzNNasIoBSWPpZslAdGMA/Kg/ZNk2LxnI/Hbnq+o6Gpf8c/jr8yCjP1DUD9Y71vZ1fxrgOzqZGyklmTpdUR2zFx1j1D4yPbnV70wLYmXFsHTaqA4vXuuuxf4NOK2Ol8E7kVbah5nNxa8FCTydpevnHmc78U4akr7op6nyRFLTTnnHsjO1VZ2ZJ2sMrefmKe/YoXrs5+UB7rXUWG65KQd4VT9Ofrpifa6rIkaDyTdjyi4+iO9hct23mRezdce+an0lGk8u48Z9u64YNsbvlVOY3xQv8sP2iTs8gVb0QnqhsNW+XiX6ofZ/U0lb6w0k/iKKgci9os0s4ehPcdro6zQugEYXSQ8cbEEiyQUhA1ptmiAl/3Wcx/LHYtDT3cd68RjQftWTRDX5CATifu/9tbxjicQU7+tHXrtrQq/im1ZkBwcfuNyxxIHxpQBFHJTUi1jEFvhY=
